name: Create test link on PR creation
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create/update test link on DEV
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '.+'
          body-template: |

            [Test link](https://sys-docs.dev.bgdi.ch/preview/%headbranch%/index.html)
          body-update-action: 'suffix'
          body-uppercase-head-match: false
